#!/bin/bash
# Definition des alias raccourcis
alias goinfre='cd /nfs/sgoinfre/goinfre/'

#composer
alias composer='php ~/composer.phar'

# Definition des alias de git
alias ga="git add"
alias gb="git branch"
alias gcm="git commit -m"
alias gco="git checkout"
alias gpl="git pull"
alias gps="git push"
alias gm="git merge"
alias gu="git add -u"
alias gusm="git submodule foreach git pull"

# Definition des alias de ls
alias l="ls"
alias ll="ls -l"
alias la="ls -lA"
alias lah="ls -lAh"
alias lh="ls -lh"
alias ls="ls -G"

# Definition des alias de compilation
alias gccf="gcc -Wall -Wextra -Werror"
alias gccl="gcc -I $LIB/includes -L $LIB -lft"
alias gcclf="gcc -Wall -Wextra -Werror -I $LIB/includes -L $LIB -lft"
alias g++f="g++ -Wall -Wextra -Werror"

# valgrind
alias vg="~/.brew/bin/valgrind"
alias vgl="vg --tool=memcheck --leak-check=full"

# Definition des alias
alias auteur="echo '$USER' > auteur"
alias clean="find . -name '*~' -execdir rm {} \;"
alias grand="open ~/GrandPerspective.app"
alias libft="cp -r $LIB .; rm -rf libft/.git"
alias modsh="vim ~/.zshrc"
alias next="source nextprev next"
alias purgevim="rf -f ~/.vim/tmp/*.swp ~/.vim/tmp/.*.swp"
alias prev="source nextprev prev"
alias rl="source ~/.zshrc"
alias rt="cd -"

function norme() { norminette $1 | sed "s/Norme/[0;1;47m[0;38;5;47mNorme/g; s/Warning/[38;5;196mWarning/g; s/Error/\[38;5;9m Error/g" }
